# DEBUG FLAGS
TRAIN_JUST_ONE_BATCH = False
TRAIN_JUST_ONE_ROUND = False
PROFILE = False
CHECK_GRADS = False

# Basic
LEARNING_RATE_DEFAULT = 1e-2    # 0.01
MAX_EPOCHS_DEFAULT = 200
EVAL_FREQ_DEFAULT = 5
BATCH_SIZE_DEFAULT = 32
WORKERS_DEFAULT = 36

OPTIMIZER_DEFAULT = 'ADAM'
WEIGHT_DECAY_DEFAULT = 0.01

DATA_DIR_DEFAULT = 'data/ny2016_0101to0331/'    # TODO
LOG_DIR_DEFAULT = 'log/'

USE_GPU_DEFAULT = 1
GPU_ID_DEFAULT = 0

NETWORK_DEFAULT = 'FeedForward'     # TODO
NETWORKS = ['FeedForward']  # TODO

MODE_DEFAULT = 'train'
EVAL_DEFAULT = 'eval.pt'   # should be a model file name
MODEL_SAVE_DIR_DEFAULT = 'model_save/'

MAX_NORM_DEFAULT = 10.0

FEAT_DIM_DEFAULT = 16   # TODO
HIDDEN_DIM_DEFAULT = 64

LOSS_FUNC_DEFAULT = 'SmoothL1Loss'
SMOOTH_L1_LOSS_BETA_DEFAULT = 10
